version: '3'
services:
  redis:
    image: redis:6.0.7
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 7399:6379

  sidecar:
    container_name: ccamp-sidecar
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis

volumes:
  redis_volume_data: